# Configuration pour l'envoi d'e-mails avec Gmail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: arona10ndiaye@gmail.com
    password: tpossdeqiuxcyhin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

            # Configuration pour l'envoi d'e-mails avec un serveur SMTP local (désactivée)
            spring:
              mail:
                host: localhost
                port: 9025
                username: ""
                password: ""
                properties:
                  mail:
                    smtp:
                      auth: false
                      starttls:
                        enable: false


            #docker run -p 9081:80 -p 9025:25 --name smtp4dev rnwood/smtp4dev:v3
            #http://localhost:9081




